# Generated by Django 5.1.4 on 2025-01-10 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIDM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrydevice',
            name='device_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('在线', '在线'), ('离线', '离线')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='IIDM.industrydevice')),
            ],
        ),
    ]
