# Generated by Django 5.1.4 on 2025-01-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIDM', '0002_alter_industrydevice_device_id_devicestatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
