# Generated by Django 5.1.4 on 2025-01-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IIDM', '0003_industryuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryuser',
            name='is_staff',
        ),
    ]
