# Generated by Django 5.1.4 on 2025-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=50)),
                ('adminPassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuId', models.IntegerField(primary_key=True, serialize=False)),
                ('stuName', models.CharField(max_length=50)),
                ('stuClass', models.CharField(max_length=50)),
                ('stuIntro', models.TextField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
