# Generated by Django 5.1.4 on 2025-01-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='adminName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='adminPassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuClass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuName',
            field=models.CharField(max_length=100),
        ),
    ]
